---
# http://kitchen.ci/docs/getting-started
# https://github.com/marcy-terui/kitchen-docker_cli
# https://github.com/neillturner/kitchen-puppet

driver:
  name: docker_cli
  skip_preparation: true
  privileged: true
  instance_container_name: false
  instance_host_name: true
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup

transport:
  name: docker_cli

provisioner:
  name: puppet_apply
  manifests_path: test/integration
  modules_path: modules
  puppet_no_sudo: true
  require_chef_for_busser: false
  require_puppet_collections: false
  require_puppet_omnibus: false
  require_puppet_repo: false

verifier:
  name: busser
  ruby_bindir: '/usr/bin'

platforms:
  # Debian 9
  - name: debian-9
    driver_config:
      image: vpgrp/puppet:debian-9
      command: /bin/systemd
suites:
  # Debian
  - name: debian
    provisioner:
      manifest: debian/init.pp
    includes:
      - debian-9
# EOF
